apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: gitops-app-dev
namePrefix: dev-
commonLabels:
  env: dev
images:
- name: gitops-app
  newName: woo0032/gitops-app
  newTag: sha-b6c503f
- name: nginx
  newName: your-dockerhub-username/gitops-app
  newTag: sha-fa7fa69

replicas:
- count: 1
  name: gitops-app
